// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.goldenet.proto;

public final class StudentProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_goldenet_proto_MyRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_goldenet_proto_MyRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_goldenet_proto_MyResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_goldenet_proto_MyResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rStudent.proto\022\021cn.goldenet.proto\"\035\n\tMy" +
                        "Request\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022" +
                        "\020\n\010realname\030\002 \001(\t2h\n\016StudentService\022V\n\025G" +
                        "etRealNameByUserName\022\034.cn.goldenet.proto" +
                        ".MyRequest\032\035.cn.goldenet.proto.MyRespons" +
                        "e\"\000B#\n\021cn.goldenet.protoB\014StudentProtoP\001" +
                        "b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_cn_goldenet_proto_MyRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_goldenet_proto_MyRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_goldenet_proto_MyRequest_descriptor,
                new java.lang.String[]{"Username",});
        internal_static_cn_goldenet_proto_MyResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_cn_goldenet_proto_MyResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_goldenet_proto_MyResponse_descriptor,
                new java.lang.String[]{"Realname",});
    }

    private StudentProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
