// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.goldenet.proto;

public interface StudentResponseListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.goldenet.proto.StudentResponseList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cn.goldenet.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<cn.goldenet.proto.StudentResponse>
    getStudentResponseList();

    /**
     * <code>repeated .cn.goldenet.proto.StudentResponse studentResponse = 1;</code>
     */
    cn.goldenet.proto.StudentResponse getStudentResponse(int index);

    /**
     * <code>repeated .cn.goldenet.proto.StudentResponse studentResponse = 1;</code>
     */
    int getStudentResponseCount();

    /**
     * <code>repeated .cn.goldenet.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<? extends cn.goldenet.proto.StudentResponseOrBuilder>
    getStudentResponseOrBuilderList();

    /**
     * <code>repeated .cn.goldenet.proto.StudentResponse studentResponse = 1;</code>
     */
    cn.goldenet.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
            int index);
}
